"""created set

Revision ID: 02218e82f318
Revises: 86cf595dbff8
Create Date: 2018-08-11 13:22:05.742393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02218e82f318'
down_revision = '86cf595dbff8'
branch_labels = ('master',)
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('set',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('id_exercise', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_exercise'], ['workout.exercise.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='workout'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('set', schema='workout')
    # ### end Alembic commands ###
