"""created exercise schema and exercise

Revision ID: 86cf595dbff8
Revises: d31d468ab947
Create Date: 2018-08-11 13:17:13.111857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86cf595dbff8'
down_revision = 'd31d468ab947'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('id_workout', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_workout'], ['workout.workout.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='workout'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exercise', schema='workout')    
    # ### end Alembic commands ###
